name: CMake
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
env:
  BUILD_TYPE: Release
 
jobs:
  world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Best Build Forever"
        files: |
          CMakeLists.txt
          ${{github.workspace}}/build/*.exe
          ${{github.workspace}}/build/*.bin
