name: CMake
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Upload Artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} Build
        path: |
          build/*.exe
          build/*.bin
          build/*.app/**/*
    - name: Upload
    - uses: actions/upload-artifact@v1
      with:
        path: ./${ { matrix.config.artifact } }
        name: ${ { matrix.config.artifact } }    
